version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout

      - run:
          name: install
          command: npm install

      - run:
          name: test
          command: npm test
